### ISSUE TITLE
User studies with AIRR volunteers

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-submission-server#23]
Incrementally evaluate the AIRR submission process with the 17 or so volunteers from the AIRR meeting.

**Comment by martinjoconnor** [comment]
Builds on initial testing performed at Yale:

https://github.com/metadatacenter/cedar-submission-server/issues/22

**Comment by graybeal** [comment]
John has to organize the initial contact, plans for which are still in discussion with Yale.

**Comment by graybeal** [comment]
3 users are in test; no others are actively volunteering at this time.

**Comment by graybeal** [comment]
Status: very close.
* CD performed some testing and has completed his participation for now.
* IT completed testing up to submission (but did not submit anything).
* JB got most of the way through submission but I have not received final word.

**Comment by martinjoconnor** [comment]
Can this be considered closed?

**Comment by graybeal** [comment]
Yes, I have the go-ahead to move the template to production when we consider it ready.

**Comment by martinjoconnor** [comment]
Is it effectively ready now then given the BioPortal branch completion?

**Comment by martinjoconnor** [comment]
Do we need to move some instances too so that we can test (first with the NCBI test repo, then with production)?

**Comment by graybeal** [comment]
Content moving task is described in https://github.com/metadatacenter/cedar-project/issues/767
