### ISSUE TITLE
Incorrect source for Cell Subset field in AIRR template

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-submission-server#35]
The MiAIRR template restricts the value to the Cell Line (CLO) ontology. 

This ontology does not have the 'naive B cell' class for example. The Cell Ontology (CL) has this value.

Which ontology should the field use?
Answer: CL

Need to update template and possibly instances.

**Comment by marcosmro** [comment]
See the ontologies recommended by the AIRR community at https://github.com/airr-community/airr-standards/issues/97

**Comment by marcosmro** [comment]
I have updated the "Cell Subset" field in the MiAIRR template to use the "lymphocyte" branch of CL.

Find the updated template at https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F4e5ce935-03ea-401a-804c-c38160c560f2
